export const CONNECT = 'connect'

export const SOCKET_CONNECTED = 'socket-connected'
export const SOCKET_OPEN = 'socket-open'
export const SOCKET_CLOSE = 'socket-close'
export const SOCKET_ERROR = 'socket-error'
export const SOCKET_PING = 'ping'
export const SOCKET_PONG = 'pong'

export const ROCKET_SUB_MESSAGES = 'stream-room-messages'
export const ROCKET_GET_ROOMS = 'rooms/get'
export const ROCKET_LOGIN = 'login'
export const ROCKET_LOAD_HISTORY = 'loadHistory'
export const ROCKET_SUBSCRIBTIONS = 'subscriptions/get'
export const ROCKET_SEND_MESSAGE = 'sendMessage'
